Support gnome-system-monitor 46
mgalgs/gnome-shell-system-monitor-applet pull request #62
Opened 2024-02-18 01:05 UTC by toupeira

The launcher filename has changed in GNOME 46.

Also drops the unused extensions app lookup.

2024-02-27 00:15 UTC, mgalgs requested changes
Thanks for the PR! Can you please share details about how this was tested (which GS versions you tested on, etc)?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/62#-:-NrbtxNU0WYBuJYh-sPR:b-eatqzj)* status: all files reviewed, 1 unresolved discussion (waiting on @toupeira)

*[a discussion](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/62#-NrbuSDN88QJQeduPrw6:-NrbuSDO8LPNunteESgJ:bxym9ab) (no related file):*
Don't we also need to add `"46"` to `metadata.json`?

___


<!-- Sent from Reviewable.io -->

2024-02-27 07:58 UTC, toupeira commented
> Thanks for the PR! Can you please share details about how this was tested (which GS versions you tested on, etc)?

Sorry I should have provided some context! :grinning: 

I'm on Debian unstable which currently has a weird mix of packages, the update to Gnome 45 isn't fully finished yet but they also already pulled in some packages from Gnome 46 Beta where possible, especially standalone apps like `gnome-system-monitor`:

- https://people.debian.org/~fpeters/gnome/debian-gnome-45-status.html
- https://people.debian.org/~fpeters/gnome/debian-gnome-46-status.html

So I'm currently on `gnome-shell` 45.3-2 from experimental (unstable still has 44) and `gnome-system-monitor` 46~beta-1.

> Don't we also need to add `"46"` to `metadata.json`?

I'll leave that up to you since I can't test it myself yet :wink: 

It looks like some other changes are still needed: https://github.com/mgalgs/gnome-shell-system-monitor-applet/issues/61

2024-02-27 17:32 UTC, mgalgs approved these changes
> So I'm currently on `gnome-shell` 45.3-2 from experimental (unstable still has 44) and `gnome-system-monitor` 46~beta-1.

Ah I see. Thanks for the explanation. In that case this looks fine to me!

> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/62#-:-NrfboCp2lAko8iFn28P:bm4xj35)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @toupeira)



<!-- Sent from Reviewable.io -->

2024-02-27 17:32 UTC, merged

2024-03-07 12:47 UTC, NVieville commented
Hello,

Maybe the first line of the metadata.json file available here:

https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/master/system-monitor-next%40paradoxxx.zero.gmail.com/metadata.json

should be replaced from:

`"shell-version": ["45"],`

to:

`"shell-version": ["45", "46"]`

in order to reflect the gnome-shell 46 compatibility.

Feel free to make any comment about this subject.

Cordially,


-- 
NVieville

2024-03-07 19:10 UTC, toupeira commented
@NVieville see https://github.com/mgalgs/gnome-shell-system-monitor-applet/issues/61 and my comment above https://github.com/mgalgs/gnome-shell-system-monitor-applet/pull/62#issuecomment-1965977127 :wink: